In [70]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [9]:
df.shape

(569, 33)

In [ ]:

df.columns = df.columns.str.strip()

# only drop if present
df.drop(columns=['id', 'Unnamed: 32'], inplace=True, errors='ignore')

In [13]:
print(df.columns.tolist())

['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']

In [14]:
df.drop(columns=['id', 'Unnamed:32'], inplace=True)
df.head()

KeyError: "['id', 'Unnamed:32'] not found in axis"

In [16]:
df.head(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state=42)

In [71]:
np.unique(y_train)

array([0, 1])

In [19]:
scaler=StandardScaler()
x_train = scaler.fit_transform(X_train)
x_test= scaler.transform(X_test)

In [20]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [22]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [23]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,0.08046,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,0.07398,...,26.680,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,0.06963,...,10.010,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,0.06329,...,12.250,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,0.06960,...,11.020,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,0.08980,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.14340,0.04786,0.2254,0.10840
106,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,0.06520,...,13.140,29.26,85.51,521.7,0.16880,0.26600,0.28730,0.12180,0.2806,0.09097
270,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.00625,0.1508,0.05376,...,14.910,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120
435,13.980,19.62,91.12,599.5,0.10600,0.11330,0.11260,0.06463,0.1669,0.06544,...,17.040,30.80,113.90,869.3,0.16130,0.35680,0.40690,0.18270,0.3179,0.10550
102,12.180,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.01770,0.1739,0.05677,...,13.340,32.84,84.58,547.8,0.11230,0.08862,0.11450,0.07431,0.2694,0.06878

In [24]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [25]:
type(y_train)

numpy.ndarray

In [26]:
type(y_test)

numpy.ndarray

numpy array to tensors

In [27]:
x_train_tensor = torch.from_numpy(x_train).to(torch.float64)
x_test_tensor = torch.from_numpy(x_test).to(torch.float64)
y_train_tensor = torch.from_numpy(y_train).to(torch.float64).view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).to(torch.float64).view(-1, 1)

In [28]:
type(x_train_tensor)

torch.Tensor

dataset and dataloader

In [73]:
from torch.utils.data import Dataset,DataLoader

In [74]:
class CustomDataset(Dataset):
    def __init__(self,features, labels):
        self.features = features
        self.labels = labels
    def __len__(self):
        return len(self.features)
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [77]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_train_tensor)

In [78]:
x_train.shape[1]

30

In [79]:
len(train_dataset)

455

In [80]:
train_dataset[2]

(tensor([-1.4000, -1.2496, -1.3452, -1.1098, -1.3326, -0.3074, -0.3656, -0.6965,
          1.9303,  0.9544,  0.0275,  1.9631, -0.1210, -0.3508,  0.5728,  0.7395,
          0.3207,  0.5895,  2.6150,  0.7189, -1.2953, -1.0408, -1.2452, -0.9997,
         -1.4387, -0.5486, -0.6449, -0.9702,  0.5976,  0.0579],
        dtype=torch.float64),
 tensor([0.], dtype=torch.float64))

In [81]:
# loader bolte train loader ar hoilo test loader 
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [30]:
import torch.nn as nn

In [31]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        self.criterion = nn.BCELoss()

    def forward(self, features):
        features = features.to(self.linear.weight.dtype)
        return self.sigmoid(self.linear(features))

    def loss_function(self, y_pred, y):
        y = y.to(y_pred.dtype)
        return self.criterion(y_pred, y)

In [32]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        self.criterion = nn.BCELoss()

    def forward(self, features):
        features = features.to(self.linear.weight.dtype)
        return self.sigmoid(self.linear(features))

    def loss_function(self, y_pred, y):
        y = y.to(y_pred.dtype)
        return self.criterion(y_pred, y)

In [33]:
epochs=25

In [35]:
loss_function=nn.BCELoss()
loss_function

BCELoss()

In [36]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
# create model
learning_rate = 0.01
model = MySimpleNN(x_train_tensor.shape[1]).double()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    
    for batch_feature,batch_level in train_loader:
        
    
    # forward pass
    #y_pred = model(x_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward + update
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8458436499016907
Epoch: 2, Loss: 0.8204336357791132
Epoch: 3, Loss: 0.7963837656173443
Epoch: 4, Loss: 0.7736295091280031
Epoch: 5, Loss: 0.752105245595885
Epoch: 6, Loss: 0.7317451056993605
Epoch: 7, Loss: 0.7124837738733552
Epoch: 8, Loss: 0.6942572055589036
Epoch: 9, Loss: 0.6770032290824293
Epoch: 10, Loss: 0.6606620181319874
Epoch: 11, Loss: 0.6451764347518385
Epoch: 12, Loss: 0.6304922529178144
Epoch: 13, Loss: 0.6165582788208671
Epoch: 14, Loss: 0.6033263865381268
Epoch: 15, Loss: 0.5907514877439041
Epoch: 16, Loss: 0.5787914524723213
Epoch: 17, Loss: 0.5674069954924229
Epoch: 18, Loss: 0.5565615401705852
Epoch: 19, Loss: 0.5462210691308694
Epoch: 20, Loss: 0.5363539687674709
Epoch: 21, Loss: 0.5269308727833784
Epoch: 22, Loss: 0.5179245084239124
Epoch: 23, Loss: 0.5093095479044797
Epoch: 24, Loss: 0.5010624666458671
Epoch: 25, Loss: 0.4931614092732928

In [38]:
x_train_tensor.shape[1]

30

In [39]:
model.parameters

<bound method Module.parameters of MySimpleNN(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
  (criterion): BCELoss()
)>

In [40]:
model = MySimpleNN(x_train_tensor.shape[1]).double()

In [41]:
# optional: run another training pass with current model
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    y_pred = model(x_train_tensor)
    loss = model.loss_function(y_pred, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5288673439096723
Epoch: 2, Loss: 0.5177599396845315
Epoch: 3, Loss: 0.5072346007993837
Epoch: 4, Loss: 0.4972508810154402
Epoch: 5, Loss: 0.4877713756741147
Epoch: 6, Loss: 0.47876153864171295
Epoch: 7, Loss: 0.47018949372484614
Epoch: 8, Loss: 0.4620258459477437
Epoch: 9, Loss: 0.45424349673667813
Epoch: 10, Loss: 0.44681746591412186
Epoch: 11, Loss: 0.4397247224652787
Epoch: 12, Loss: 0.43294402528889403
Epoch: 13, Loss: 0.4264557745617988
Epoch: 14, Loss: 0.42024187390818546
Epoch: 15, Loss: 0.4142856032454304
Epoch: 16, Loss: 0.40857150195516095
Epoch: 17, Loss: 0.4030852618805922
Epoch: 18, Loss: 0.39781362956127514
Epoch: 19, Loss: 0.39274431706973106
Epoch: 20, Loss: 0.38786592079922294
Epoch: 21, Loss: 0.38316784755888367
Epoch: 22, Loss: 0.37864024735444324
Epoch: 23, Loss: 0.3742739522644591
Epoch: 24, Loss: 0.37006042085929686
Epoch: 25, Loss: 0.3659916876501897

In [42]:
model.linear.weight.shape

torch.Size([1, 30])

In [43]:
model.linear.bias.shape

torch.Size([1])

training pipeline 
parameters

In [44]:
learning_rate = 0.01
num_epochs = 25

In [ ]:
# Deprecated experimental cell removed to avoid overriding MySimpleNN.
pass

In [100]:
epochs=50

In [45]:
# create model
learning_rate = 0.01
model = MySimpleNN(x_train_tensor.shape[1]).double()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model(x_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward + update
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8245354043406073
Epoch: 2, Loss: 0.8002867961576925
Epoch: 3, Loss: 0.7773756682526035
Epoch: 4, Loss: 0.7557310650729987
Epoch: 5, Loss: 0.7352823083584764
Epoch: 6, Loss: 0.7159598131559456
Epoch: 7, Loss: 0.6976957436489901
Epoch: 8, Loss: 0.6804245348088825
Epoch: 9, Loss: 0.6640832957982082
Epoch: 10, Loss: 0.6486121055102925
Epoch: 11, Loss: 0.6339542091939803
Epoch: 12, Loss: 0.6200561261126321
Epoch: 13, Loss: 0.6068676799289623
Epoch: 14, Loss: 0.5943419648499558
Epoch: 15, Loss: 0.5824352609905126
Epoch: 16, Loss: 0.5711069118760703
Epoch: 17, Loss: 0.5603191757218725
Epoch: 18, Loss: 0.5500370604064696
Epoch: 19, Loss: 0.5402281501841307
Epoch: 20, Loss: 0.5308624303676694
Epoch: 21, Loss: 0.5219121145909654
Epoch: 22, Loss: 0.5133514778913101
Epoch: 23, Loss: 0.5051566977483634
Epoch: 24, Loss: 0.4973057043614023
Epoch: 25, Loss: 0.48977804080675985

evalution

In [62]:
model = MySimpleNN(x_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )
batch_size = 32
epoch=25 
n_samples = len(x_train_tensor)
for epoch in range(num_epochs):
    for start_indx in range(0,n_samples, batch_size):
        end_indx = start_indx + batch_size
        print(f'{start_indx} to {end_indx}')
        x_batch = x_train_tensor[start_indx:end_indx]
        y_batch = y_train_tensor[start_indx:end_indx]
        
        # forward pass
        y_pred = model(x_batch)
        
        # loss calculate
        loss = model.loss_function(y_pred, y_batch)
        
        # backward + update
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480
0 to 32
32 to 64
64 to 96
96 to 128
128 to 160
160 to 192
192 to 224
224 to 256
256 to 288
288 to 320
320 to 352
352 to 384
384 to 416
416 to 448
448 to 480

In [66]:
# model evaluat\`\4`4`4`4```````22q`323q3```````42q3`23`q4ion
with torch.no_grad():
    y_pred = model(x_test_tensor)
    y_pred = (y_pred > 0.5).to(torch.float64)
    accuracy = (y_pred == y_test_tensor).to(torch.float64).mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.9736842105263158

In [67]:
! pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [68]:
from torchinfo import summary

In [69]:
summary(model, input_size=(455, 30), dtypes=[torch.float64])

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.11
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.11
==========================================================================================