In [11]:
import pandas as pd
df = pd.read_csv('IMDB Dataset.csv',encoding='latin-1',engine='python',on_bad_lines='skip')

In [12]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
df.loc[2, 'review'].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [14]:
df['review'] = df['review'].str.replace('<br />', ' ', regex=False)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production.   The filming t...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [15]:
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production.   The filming t...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [16]:
import re 
def removal_html_tags(text):
    pattern = re.compile(r'<.*?>')
    return pattern.sub(r'', text)

In [17]:
removal_html_tags(df.loc[0, 'review'])

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.  The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.  It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.  I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [20]:
df['review']=df['review'].apply(removal_html_tags)
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production.   The filming t...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [21]:
def remove_url(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [22]:
text1="This is a sample text with a URL: https://www.example.com and another one www.test.com"
cleaned_text = remove_url(text1)
print(cleaned_text)

This is a sample text with a URL:  and another one

In [23]:
import string

In [24]:
exclude =string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [31]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,"")
        print(char)

In [32]:
remove_punc("Hello, World! This is a test.")

!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
:
;
<
=
>
?
@
[
\
]
^
_
`
{
|
}
~

In [33]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [34]:
remove_punc1("Hello, World! This is a test.")

'Hello World This is a test'

In [35]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [39]:
def chat_conversation(text):
    new_text = []
    for word in text.split():
        if word.upper() in chat_words:
            new_text.append(chat_words[word.upper()])
        else:
            new_text.append(word)
    return ' '.join(new_text)

In [41]:
chat_conversation("OMG! I can't believe it. This is so funny, LOL!")

"Oh My God I can't believe it. This is so funny, LOL!"

In [42]:
from textblob import TextBlob
text = "I love this movie! It's amazing and fantastic."
blob = TextBlob(text)
sentiment = blob.sentiment
print(sentiment)

Sentiment(polarity=0.5416666666666666, subjectivity=0.7999999999999999)

In [ ]:
text = "Check out my website at https://www.example.com for more information."

In [43]:
import nltk 
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
print(stop_words)

{'into', 'those', 'during', "he's", 'from', 'who', 'down', 'after', 'was', 'above', "i'd", 'll', 'do', "couldn't", 'then', "that'll", "i'm", 'its', 's', 'hadn', 'herself', 'most', 'than', 'does', 'very', 'haven', 'some', 'here', "he'll", "they're", "they've", 'how', 'a', 'few', 'my', "don't", 'such', 'nor', 'their', 'with', 'will', 'over', 'doesn', 'weren', 'the', 'yourselves', 'only', 'we', 'wasn', "aren't", 'been', "you're", 'didn', 'out', 't', 'wouldn', 'an', 'hasn', 'himself', 'i', 'shan', 'just', 'in', 'be', "it'll", 'me', 'on', 'y', "she's", "i'll", "hadn't", 'd', 'more', "should've", 'any', 'were', 'can', "he'd", 'at', 'while', 'you', 'what', 'now', 'him', 'isn', "we're", 'because', 'needn', "i've", 'under', "hasn't", 'theirs', "we've", 'but', 've', 'aren', "wasn't", 'did', 'mightn', 'and', "doesn't", 'don', "isn't", 'm', "they'll", 'ain', 'being', 'shouldn', 'too', 'where', 'they', 'mustn', 'he', "it's", "shan't", "we'll", 'these', 'between', 'your', 'for', "we'd", 'before', 'all', "needn't", 'as', 'her', 'had', 'again', 'yourself', 'of', 'off', 'each', 'having', "you've", 'further', 'it', 'doing', 'our', 'that', 'or', "weren't", "it'd", 'ours', 'about', 'if', 'through', 'is', 'until', 'myself', 'she', 'should', 'his', "she'll", 'when', "shouldn't", 'o', 'against', 'are', 'this', 'both', "they'd", 'ma', 'to', 'has', 'once', 'there', 'why', 'itself', 'whom', "she'd", 'hers', 're', "you'd", "you'll", 'ourselves', "mightn't", "didn't", 'have', 'won', 'up', "wouldn't", 'them', 'other', 'by', 'themselves', 'yours', "mustn't", "won't", 'no', 'not', 'below', 'same', 'own', 'so', "haven't", 'am', 'couldn', 'which'}

[nltk_data] Downloading package stopwords to /Users/imac/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [44]:
stop_words = set(stopwords.words('bengali'))
print(stop_words)

{'কী', 'অন্তত', 'দিয়েছেন', 'কবে', 'তিনিও', 'অনুযায়ী', 'প্রাথমিক', 'অনেকে', 'কারও', 'উপর', 'দিতে', 'এর', 'করবেন', 'বললেন', 'দিয়ে', 'হোক', 'জানানো', 'সব', 'যেখানে', 'সেই', 'যথেষ্ট', 'একে', 'ফিরে', 'কয়েক', 'বদলে', 'তেমন', 'চেষ্টা', 'আমাদের', 'উপরে', 'আবার', 'মোট', 'করছে', 'এব', 'এমন', 'বার', 'হলে', 'কয়েকটি', 'হয়নি', 'হওয়ায়', 'যাওয়ার', 'বক্তব্য', 'অর্থাত', 'সেটাই', 'মনে', 'সুতরাং', 'এমনি', 'রেখে', 'থাকায়', 'পরেই', 'কাছে', 'এদের', 'বা', 'দেওয়ার', 'শুরু', 'কাজে', 'অন্য', 'এতটাই', 'সে', 'মধ্যে', 'অবধি', 'যার', 'তাঁদের', 'হলো', 'হবে', 'ছাড়া', 'করবে', 'জানিয়েছে', 'নিয়ে', 'করিতে', 'গিয়ে', 'বাদে', 'পারে', 'যা', 'মধ্যভাগে', 'আগেই', 'জানতে', 'ভাবে', 'আর', 'যেতে', 'এক্', 'পরেও', 'বলেছেন', 'এখানে', 'যদিও', 'বলে', 'জে', 'এখানেই', 'যখন', 'সি', 'তারা', 'নেওয়ার', 'কমনে', 'বেশি', 'হত', 'এবং', 'তারপর', 'দুটি', 'সবার', 'জনের', 'হতেই', 'ছাড়াও', 'দুটো', 'ওঁদের', 'প্রায়', 'কোনো', 'আমরা', 'ফলে', 'একই', 'হয়েছিল', 'না', 'কাউকে', 'জনকে', 'ও', 'তার', 'গিয়েছে', 'হওয়ার', 'সেটা', 'নাকি', 'হতে', 'তখন', 'চায়', 'কত', 'টি', 'যায়', 'আমি', 'যতটা', 'প্রভৃতি', 'হলেও', 'একটি', 'কে', 'যাকে', 'করার', 'হওয়া', 'অনেকেই', 'গিয়ে', 'রয়েছে', 'থাকা', 'সেটাও', 'আজ', 'উত্তর', 'হয়েছে', 'তথা', 'যাবে', 'সাধারণ', 'মতোই', 'কিছু', 'লক্ষ', 'সামনে', 'দু', 'র', 'চার', 'বেশ', 'সহ', 'কোন', 'তাহার', 'যেন', 'হয়তো', 'আপনার', 'মাত্র', 'বন', 'নয়', 'সমস্ত', 'তবু', 'করেই', 'হইয়া', 'কাছ', 'দেখা', 'যাওয়া', 'কি', 'ঠিক', 'সঙ্গেও', 'এরা', 'এত', 'নেই', 'চালু', 'হন', 'কিন্তু', 'যত', 'স্পষ্ট', 'উচিত', 'দেখতে', 'আগামী', 'তত', 'ওর', 'পর্যন্ত', 'চান', 'যাওয়া', 'বহু', 'জানিয়ে', 'দিকে', 'যান', 'এটাই', 'করেন', 'যাদের', 'করেছে', 'ওঁরা', 'ক্ষেত্রে', 'তোমার', 'তুলে', 'করায়', 'তাদের', 'কিংবা', 'থাকে', 'এল', 'তাঁাহারা', 'গেলে', 'নতুন', 'বিশেষ', 'রকম', 'তাও', 'মাধ্যমে', 'তাহা', 'নিজেদের', 'নিতে', 'নাই', 'ব্যবহার', 'বলা', 'এই', 'কেউই', 'হৈলে', 'জানায়', 'গেছে', 'জন্যওজে', 'কোটি', 'এটি', 'তো', 'মধ্যেও', 'কিছুই', 'তাহাতে', 'ভাবেই', 'নেওয়া', 'পি', 'পেয়্র্', 'আরও', 'দিয়েছে', 'রাখা', 'হয়েই', 'আছে', 'হইবে', 'আপনি', 'কেন', 'নিজের', 'তাতে', 'থাকেন', 'আমাকে', 'তিনি', 'ধরে', 'আই', 'কারণ', 'নয়', 'পারি', 'নানা', 'ওই', 'একবার', 'এতে', 'করা', 'তিনঐ', 'থাকবেন', 'প্রায়', 'পক্ষে', 'যাঁর', 'অনেক', 'ওখানে', 'করেছিলেন', 'তুমি', 'যাঁরা', 'এবার', 'এখন', 'ফের', 'নিজেই', 'নিয়ে', 'করি', 'ছিল', 'বলেন', 'হয়েছেন', 'তাকে', 'করিয়া', 'ওঁর', 'শুধু', 'কেউ', 'পেয়ে', 'যাতে', 'তাহলে', 'দেখে', 'হয়', 'বিনা', 'আদ্যভাগে', 'প্রথম', 'ওদের', 'গুলি', 'যারা', 'এমনকী', 'ওরা', 'আগে', 'তবে', 'দিলেন', 'করে', 'বলতে', 'বরং', 'এস', 'অথচ', 'পাওয়া', 'অথবা', 'থেকে', 'বসে', 'যিনি', 'গোটা', 'করিয়ে', 'বলল', 'এঁদের', 'দেন', 'গেল', 'পরে', 'ব্যাপারে', 'দ্বারা', 'কাজ', 'পারেন', 'এসে', 'আমার', 'বি', 'হয়ে', 'নেওয়া', 'মতো', 'হলেই', 'ই', 'তাঁর', 'সঙ্গে', 'খুব', 'ইত্যাদি', 'জানা', 'করছেন', 'করতে', 'অবশ্য', 'পর', 'জ্নজন', 'ঐ', 'হিসাবে', 'থেকেই', 'নিজে', 'হচ্ছে', 'হল', 'ইহা', 'উনি', 'করাই', 'তাঁকে', 'প্রযন্ত', 'থাকবে', 'কয়েক', 'এটা', 'কোনও', 'হইতে', 'যেমন', 'ধামার', 'যদি', 'দেওয়া', 'সেখানে', 'যাচ্ছে', 'সহিত', 'ছিলেন', 'কেখা', 'যে', 'ওকে', 'সেখান', 'জন্য', 'তা', 'করলে', 'করেছেন', 'দেওয়া', 'এখনও', 'চলে', 'মোটেই', 'দিন', 'সেটি', 'দেয়', 'এ', 'তাঁরা', 'স্বয়ং', 'তাই', 'বিভিন্ন', 'পাচ', 'হবেন', 'কখনও', 'বিষয়টি', 'প্রতি', 'তারৈ', 'চেয়ে', 'করলেন', 'থেকেও', 'হাজার', 'জন', 'নাগাদ', 'এঁরা', 'অতএব', 'সম্প্রতি', 'হয়', 'ধরা', 'দুই', 'মধ্যেই'}

In [45]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'into', 'those', 'during', "he's", 'from', 'who', 'down', 'after', 'was', 'above', "i'd", 'll', 'do', "couldn't", 'then', "that'll", "i'm", 'its', 's', 'hadn', 'herself', 'most', 'than', 'does', 'very', 'haven', 'some', 'here', "he'll", "they're", "they've", 'how', 'a', 'few', 'my', "don't", 'such', 'nor', 'their', 'with', 'will', 'over', 'doesn', 'weren', 'the', 'yourselves', 'only', 'we', 'wasn', "aren't", 'been', "you're", 'didn', 'out', 't', 'wouldn', 'an', 'hasn', 'himself', 'i', 'shan', 'just', 'in', 'be', "it'll", 'me', 'on', 'y', "she's", "i'll", "hadn't", 'd', 'more', "should've", 'any', 'were', 'can', "he'd", 'at', 'while', 'you', 'what', 'now', 'him', 'isn', "we're", 'because', 'needn', "i've", 'under', "hasn't", 'theirs', "we've", 'but', 've', 'aren', "wasn't", 'did', 'mightn', 'and', "doesn't", 'don', "isn't", 'm', "they'll", 'ain', 'being', 'shouldn', 'too', 'where', 'they', 'mustn', 'he', "it's", "shan't", "we'll", 'these', 'between', 'your', 'for', "we'd", 'before', 'all', "needn't", 'as', 'her', 'had', 'again', 'yourself', 'of', 'off', 'each', 'having', "you've", 'further', 'it', 'doing', 'our', 'that', 'or', "weren't", "it'd", 'ours', 'about', 'if', 'through', 'is', 'until', 'myself', 'she', 'should', 'his', "she'll", 'when', "shouldn't", 'o', 'against', 'are', 'this', 'both', "they'd", 'ma', 'to', 'has', 'once', 'there', 'why', 'itself', 'whom', "she'd", 'hers', 're', "you'd", "you'll", 'ourselves', "mightn't", "didn't", 'have', 'won', 'up', "wouldn't", 'them', 'other', 'by', 'themselves', 'yours', "mustn't", "won't", 'no', 'not', 'below', 'same', 'own', 'so', "haven't", 'am', 'couldn', 'which'}